# In this scenario:
# - There is one order of one tray.
# - There are no faulty parts.
# - The belt is not used.
# - There's no need to flip any part.

options:
  insert_models_over_bins: true
  fill_demo_tray: false
  gazebo_state_logging: false
  model_type_aliases:
    order_part1: piston_rod_part
    order_part2: gear_part
    order_part3: pulley_part
    order_part4: disk_part

orders:
  order_0:
    announcement_condition: time
    announcement_condition_value: 0.0
    kit_count: 1
    parts:
      part_0:
        type: order_part1
        pose:
          xyz: [0.1, -0.18, 0]
          rpy: [0, 0, 0]
      part_1:
        type: order_part2
        pose:
          xyz: [-0.12, -0.2, 0]
          rpy: [0, 0, 0]

models_over_bins:
  bin5:
    models:
      piston_rod_part:
        xyz_start: [0.21, 0.21, 0.0]
        xyz_end: [0.41, 0.41, 0.0]
        rpy: [0, 0, 'pi/4']
        num_models_x: 2
        num_models_y: 2

  bin6:
    models:
       gear_part:
        xyz_start: [0.13, 0.13, 0.0]
        xyz_end: [0.53, 0.53, 0.0]
        rpy: [0, 0, 0]
        num_models_x: 4
        num_models_y: 4

  bin7:
    models:
      disk_part:
        xyz_start: [0.14, 0.14, 0.0]
        xyz_end: [0.46, 0.46, 0.0]
        rpy: [0, 0, 'pi/4']
        num_models_x: 2
        num_models_y: 2

  bin8:
    models:
      pulley_part:
        xyz_start: [0.14, 0.14, 0.0]
        xyz_end: [0.46, 0.46, 0.0]
        rpy: [0, 0, 'pi/4']
        num_models_x: 2
        num_models_y: 2

time_limit: 500
